# -*- coding: utf-8 -*-
"""Dataset_Exploration.ipynb

Automatically generated by Colab. """

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

pd.set_option('display.max_columns', None)

df_uci = pd.read_csv(r'/content/drive/MyDrive/Dropout Prediction/datasets/data.csv',sep=';')

print(df_uci.shape)
df_uci.head()

df_uci.info()

df_uci.describe()

df_uci.isnull().sum()

df_uci.columns.tolist()

df_uci['Target'].value_counts()

sns.countplot(x='Target', data=df_uci)
plt.title('Dropout Distribution')
plt.show()

plt.figure(figsize=(18,10))
numeric_df = df_uci.select_dtypes(include=['number'])
sns.heatmap(numeric_df.corr(), cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(12,6))
sns.heatmap(df_uci.isnull(), cbar=False)
plt.title('Missing Value Heatmap')
plt.show()

df_uci = pd.read_csv(r'/content/drive/MyDrive/Dropout Prediction/datasets/dataset.csv')

print(df_uci.shape)
df_uci.head()

df_uci.info()

df_uci.describe()

df_uci.isnull().sum()

df_uci.columns.tolist()

df_uci['Target'].value_counts()

sns.countplot(x='Target', data=df_uci)
plt.title('Dropout Distribution')
plt.show()

plt.figure(figsize=(18,10))
numeric_df = df_uci.select_dtypes(include=['number'])
sns.heatmap(numeric_df.corr(), cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(12,6))
sns.heatmap(df_uci.isnull(), cbar=False)
plt.title('Missing Value Heatmap')
plt.show()

# Reload datasets properly

df_uci = pd.read_csv(r'/content/drive/MyDrive/Dropout Prediction/datasets/data.csv',sep=';')

df_kaggle = pd.read_csv(r'/content/drive/MyDrive/Dropout Prediction/datasets/dataset.csv')

print("UCI Shape:", df_uci.shape)
print("Kaggle Shape:", df_kaggle.shape)

print("===== UCI Columns =====")
for col in df_uci.columns:
    print(col)

print("\n===== Kaggle Columns =====")
for col in df_kaggle.columns:
    print(col)

plt.figure(figsize=(8,5))
sns.countplot(x='Target', data=df_uci)

plt.title("Target Distribution")
plt.xlabel("Student Status")
plt.ylabel("Count")

plt.show()

important_cols = [
    'Admission grade',
    'Age at enrollment',
    'Curricular units 1st sem (grade)',
    'Curricular units 2nd sem (grade)'
]

for col in important_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x='Target', y=col, data=df_uci)
    plt.title(col)
    plt.show()

for col in df_uci.columns:
    print("\n====================")
    print(col)
    print(df_uci[col].value_counts().head(10))

# ==================================
# FEATURE SELECTION
# ==================================

drop_cols = [
    'Nacionality',
    'International',
    'Unemployment rate',
    'Inflation rate',
    'GDP',
    'Application order'
]

df_model = df_uci.drop(columns=drop_cols)

print(df_model.shape)
df_model.head()

target_map = {
    'Graduate': 0,
    'Enrolled': 1,
    'Dropout': 2
}

df_model['Target'] = df_model['Target'].map(target_map)

df_model['Target'].value_counts()

correlation = df_model.corr()['Target'].sort_values(ascending=False)

plt.figure(figsize=(10,12))
correlation.drop('Target').plot(kind='barh')

plt.title("Feature Correlation With Dropout Risk")
plt.show()

from sklearn.ensemble import RandomForestClassifier

X = df_model.drop('Target', axis=1)
y = df_model['Target']

rf = RandomForestClassifier(random_state=42)
rf.fit(X, y)

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance.head(20))

# ==================================
# MODEL DATASET PREPARATION
# ==================================

drop_cols = [
    'Nacionality',
    'International',
    'Unemployment rate',
    'Inflation rate',
    'GDP',
    'Application order'
]

df_model = df_uci.drop(columns=drop_cols)

print(df_model.shape)

target_map = {
    'Graduate': 0,
    'Enrolled': 1,
    'Dropout': 2
}

df_model['Target'] = df_model['Target'].map(target_map)

df_model['Target'].value_counts()

from sklearn.model_selection import train_test_split

X = df_model.drop('Target', axis=1)
y = df_model['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:")
print(accuracy_score(y_test, pred))

print("\nClassification Report")
print(classification_report(y_test, pred))

plt.figure(figsize=(8,6))

sns.heatmap(
    confusion_matrix(y_test, pred),
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# ==================================
# BINARY CLASSIFICATION MODEL
# ==================================

df_binary = df_model.copy()

df_binary['Target'] = df_binary['Target'].replace({
    0: 0,   # Graduate = Safe
    1: 0,   # Enrolled = Safe
    2: 1    # Dropout = Risk
})

df_binary['Target'].value_counts()

from sklearn.model_selection import train_test_split

X = df_binary.drop('Target', axis=1)
y = df_binary['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.ensemble import RandomForestClassifier

rf_binary = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

rf_binary.fit(X_train, y_train)

pred_binary = rf_binary.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:")
print(accuracy_score(y_test, pred_binary))

print("\nClassification Report")
print(classification_report(y_test, pred_binary))

plt.figure(figsize=(7,5))

sns.heatmap(
    confusion_matrix(y_test, pred_binary),
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Binary Classification Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

!pip install xgboost lightgbm catboost -q

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

models = {

    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=300,
            random_state=42
        ),

    "XGBoost":
        XGBClassifier(
            random_state=42,
            eval_metric='logloss'
        ),

    "LightGBM":
        LGBMClassifier(
            random_state=42
        ),

    "CatBoost":
        CatBoostClassifier(
            verbose=0,
            random_state=42
        ),

    "Neural Network":
        MLPClassifier(
            hidden_layer_sizes=(100,50),
            max_iter=1000,
            random_state=42
        )
}

results = []

for name, model in models.items():

    print(f"Training {name}...")

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, pred)

    precision = precision_score(y_test, pred)

    recall = recall_score(y_test, pred)

    f1 = f1_score(y_test, pred)

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1
    ])

results_df = pd.DataFrame(
    results,
    columns=[
        'Model',
        'Accuracy',
        'Precision',
        'Recall',
        'F1 Score'
    ]
)

results_df.sort_values(
    by='Recall',
    ascending=False
)

results_df.set_index('Model').plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("Hybrid Model Comparison")
plt.ylabel("Score")
plt.xticks(rotation=45)

plt.show()

# ==================================
# FEATURE ENGINEERING
# ==================================

df_deploy = df_uci.copy()

# Binary target
df_deploy['Target'] = df_deploy['Target'].replace({
    'Graduate': 0,
    'Enrolled': 0,
    'Dropout': 1
})

# Create backlog approximation
df_deploy['Backlogs'] = (
    df_deploy['Curricular units 1st sem (enrolled)']
    - df_deploy['Curricular units 1st sem (approved)']
)

# Attendance proxy
df_deploy['Academic Engagement'] = (
    df_deploy['Curricular units 1st sem (evaluations)']
    / (df_deploy['Curricular units 1st sem (enrolled)'] + 1)
)

# Semester performance
df_deploy['Academic Performance'] = (
    (
        df_deploy['Curricular units 1st sem (grade)']
        +
        df_deploy['Curricular units 2nd sem (grade)']
    ) / 2
)

df_deploy.head()

# ==================================
# DEPLOYMENT FEATURE DATASET
# ==================================

df_final = pd.DataFrame()

# Basic Info
df_final['Age'] = df_uci['Age at enrollment']
df_final['Gender'] = df_uci['Gender']

# Academic
df_final['Admission_Score'] = df_uci['Admission grade']

df_final['Subjects_Enrolled'] = (
    df_uci['Curricular units 1st sem (enrolled)']
)

df_final['Subjects_Passed'] = (
    df_uci['Curricular units 1st sem (approved)']
)

df_final['Backlogs'] = (
    df_final['Subjects_Enrolled']
    - df_final['Subjects_Passed']
)

df_final['Semester_GPA'] = (
    (
        df_uci['Curricular units 1st sem (grade)']
        +
        df_uci['Curricular units 2nd sem (grade)']
    ) / 2
)

# Financial
df_final['Fees_Paid'] = (
    df_uci['Tuition fees up to date']
)

df_final['Scholarship'] = (
    df_uci['Scholarship holder']
)

# Family
df_final['Mother_Education'] = (
    df_uci["Mother's qualification"]
)

df_final['Father_Education'] = (
    df_uci["Father's qualification"]
)

# Engagement
df_final['Academic_Engagement'] = (
    df_uci['Curricular units 1st sem (evaluations)']
    /
    (
        df_uci[
            'Curricular units 1st sem (enrolled)'
        ] + 1
    )
)

# Target
df_final['Target'] = df_uci['Target'].replace({
    'Graduate': 0,
    'Enrolled': 0,
    'Dropout': 1
})

df_final.head()

df_final.info()
df_final.describe()

# ==================================
# DEPLOYMENT MODEL TRAINING
# ==================================

from sklearn.model_selection import train_test_split

X = df_final.drop('Target', axis=1)
y = df_final['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=300,
    learning_rate=0.05,
    depth=6,
    verbose=0,
    random_state=42
)

cat_model.fit(X_train, y_train)

pred = cat_model.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:")
print(accuracy_score(y_test, pred))

print("\nClassification Report")
print(classification_report(y_test, pred))

plt.figure(figsize=(7,5))

sns.heatmap(
    confusion_matrix(y_test, pred),
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Final Deployment Model")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

!pip install shap -q

import shap

explainer = shap.TreeExplainer(cat_model)

shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(10,6))

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar"
)

student_index = 10

shap.force_plot(
    explainer.expected_value,
    shap_values[student_index],
    X_test.iloc[student_index],
    matplotlib=True
)

# ==================================
# SAVE FINAL MODEL
# ==================================

import joblib

# Save trained model
joblib.dump(
    cat_model,
    'catboost_dropout_model.pkl'
)

print("Model saved successfully")

feature_names = X.columns.tolist()

joblib.dump(
    feature_names,
    'feature_names.pkl'
)

print(feature_names)

sample_input = X.head(1)

sample_input.to_csv(
    'sample_input_template.csv',
    index=False
)

print("Template saved")

from google.colab import files

files.download('catboost_dropout_model.pkl')
files.download('feature_names.pkl')
files.download('sample_input_template.csv')
